management:
  endpoint:
    health:
      show-components: always
      show-details: always
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

spring:
  data:
    rest:
      basePath: /data
  datasource:
    driver-class-name: org.h2.Driver
    # TODO: Is close-on-exit a bandaid?
    url: jdbc:h2:mem:demo;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      printer:
        enabled: true
  h2:
    console:
      path: /h2
  main:
    banner-mode: off
  sql:
    init:
      data-locations: classpath:sql/data.sql
      schema-locations: classpath:sql/schema.sql
      mode: always

springdoc:
  show-actuator: true
  model-and-view-allowed: true
  writer-with-default-pretty-printer: true
  swagger-ui:
    path: /rest
