management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: "*"

spring:
  data:
    rest:
      basePath: /data
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1
    username: sa
    password: password
  h2:
    console:
      path: /h2
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always
